# fly.toml app configuration file generated for akar-kuadrat on 2023-10-02T22:10:42+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "akar-kuadrat"
primary_region = "sin"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
